FROM golang:1.9.2-alpine3.6

RUN apk update
RUN apk add --virtual build-dependencies build-base git
ADD . $GOPATH/src/github.com/yoheimuta/go-warmcache
RUN go install github.com/yoheimuta/go-warmcache/example
RUN apk del build-dependencies && rm -rf /var/cache/apk/*
